config/routes.rb
Tiralabra::Application.routes.draw do
  resources :sorts

  root to: 'sorts#index'

  

end

app/models/sort.rb
class Sort < ActiveRecord::Base

	#Bubblesort
	def self.bubble(list)
		list.each_index do |i|
			(list.length - i - 1).times do |k|
				if list[k] > list[k + 1]
					#Ruby parallel assignment (swap)
					list[k], list[k + 1] = list[k + 1], list[k]
				end
			end
		end
	end

	#Quicksort
	def self.quick_sort(list)
		#Initialize a clone list for operations
		sl = list.clone
		#Already in order
		return sl if sl.size <= 1
		pivot = sl.pop
		#Using Ruby built-in partition
		left, right = sl.partition { |e| e < pivot }
		#Recursive calls for the both sides using pivot
		quick_sort(left) + [pivot] + quick_sort(right)
	end

	#Mergesort
	def self.merge_sort(list)
		#Already in order
		return list if list.size < 2
		#Divide and conquer, split the list and halves
		left = list[0, list.length/2]
		right = list[list.length/2, list.length]

		merge(merge_sort(left), merge_sort(right))
	end

	#Merge-operation
	def self.merge(left, right)
		sorted_list = []
		until left.empty? || right.empty?
			#If left <= right index, add left, else right to the sorted list
			sorted_list << (left[0] <= right[0] ? left.shift : right.shift)
		end
		#Return concatenated list
		sorted_list.concat(left).concat(right)
	end

	#Insertion sort
	def self.insert_sort(list)
		for i in 1..(list.length - 1)
			x = list[i]
			j = i - 1
			while j >= 0 and list[j] > x
				list[j + 1] = list[j] 
				j -= 1
			end
			list[j + 1] = x
		end
		list
	end

  #Fill the list in random, ascdening or descending order
  def self.populate(cond, inp)
  	if cond == 'random'
  		(0..inp.to_i).to_a.sort{ rand() - 0.5 }[0..inp.to_i]
  	elsif cond == 'desc'
  		Array.new(inp.to_i) { |i| (inp.to_i)-i }
  	elsif cond == 'asc'
  		(0..inp.to_i).to_a
  	end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sorts_controller.rb
require 'benchmark'
include Benchmark
require 'bigdecimal/math'

class SortsController < ApplicationController
  before_action :set_sort, only: [:show, :edit, :update, :destroy]

  # GET /sorts
  # GET /sorts.json
  def index
    @sort = Sort.new
    #Get the average run-times
    @sort.bubble = Sort.average('bubble')
    @sort.quick = Sort.average('quick')
    @sort.merge = Sort.average('merge')
    @sort.insertion = Sort.average('insertion')
  end

  # GET /sorts/1
  # GET /sorts/1.json
  def show

  end

  # GET /sorts/new
  def new
    @sort = Sort.new
  end

  # GET /sorts/1/edit
  def edit
  end

  # POST /sorts
  # POST /sorts.json
  def create
    @sort = Sort.new(sort_params)
    @sort.name = params[:name]
    @sort.input = params[:input]

    list = Sort.populate(params[:name], params[:input])
    #org = list
    #p org

    mergeList = list
    quickList = list
    insertList = list

    #p "Mergelist before: #{mergeList}"
    merge = Benchmark.realtime do 
      mergeList = Sort.merge_sort(mergeList)
    end
    #p "Mergelist after: #{mergeList}"

    #p "Quick before: #{quickList}"
    quick = Benchmark.realtime do 
      quickList = Sort.quick_sort(quickList)
    end
    #p "Quick after: #{quickList}"

    #p "Bubble before: #{list}"
    bubble = Benchmark.realtime do 
      list = Sort.bubble(list)
    end
    #p "Bubble after: #{list}"

    #p "Insertion before: #{insertList}"
    insertion = Benchmark.realtime do 
      insertList = Sort.insert_sort(insertList)
    end
    #p "Insertion after: #{insertList}"

    #convert to milliseconds
    @sort.quick = quick*1000
    @sort.bubble = bubble*1000
    @sort.merge = merge*1000
    @sort.insertion = insertion*1000

    respond_to do |format|
      if @sort.save
        format.html { redirect_to @sort, notice: "Quicksort: #{quick*1000}ms, Mersort: #{merge*1000}ms, Bubblesort: #{bubble*1000}ms, Insertion sort: #{insertion*1000}ms" }
        format.json { render action: 'show', status: :created, location: @sort }
      else
        format.html { render action: 'new' }
        format.json { render json: @sort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sorts/1
  # PATCH/PUT /sorts/1.json
  def update
    respond_to do |format|
      if @sort.update(sort_params)
        format.html { redirect_to @sort, notice: 'Sort was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sorts/1
  # DELETE /sorts/1.json
  def destroy
    @sort.destroy
    respond_to do |format|
      format.html { redirect_to sorts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sort
      @sort = Sort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sort_params
      params.fetch(:sort, {}).permit(:name, :input) 
    end



  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sorts_helper.rb
module SortsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tiralabra" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Tiralabra</a>
          <div class="container-fluid nav-collapse">
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
          <%= bootstrap_flash %>
          <%= yield %>
    </div><!--/row-->

      <footer>
        <p>&copy; Tiralabra 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/sorts/_form.html.erb
<%= form_for Sort.new do |f| %>
  <% if @sort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sort.errors.count, "error") %> prohibited this sort from being saved:</h2>

      <ul>
      <% @sort.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Fill the array" %>
    <%= radio_button_tag :name, 'asc', true %>
    <%= label_tag(:name_ascending, "Ascending (already in order)", :style => "display:inline") %><br>
    <%= radio_button_tag :name, 'desc' %>
    <%= label_tag(:name_descending, "Descending", :style => "display:inline") %><br>
    <%= radio_button_tag :name, 'random' %>
    <%= label_tag(:name_random, "Random", :style => "display:inline") %> 
  </div>

  <div class="field">
    <%= f.label "Input size" %>
    <%= number_field_tag :input, 3, in: 3...15000 %>
  </div>


  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/sorts/edit.html.erb
<h1>Editing sort</h1>

<%= render 'form' %>

<%= link_to 'Show', @sort %> |
<%= link_to 'Back', sorts_path %>

app/views/sorts/index.html.erb
<h1>Create a new sort</h1>
<%= render 'form' %>
<h1>Average sort times in milliseconds</h1>
<%= content_tag :div, "", id: "average", data: {sort: @sort} %>
<div>
<h3>Quick sort worst case O(n²) and best O(n log n)</h3>
<h3>Merge sort worst case and best case O(n log n)</h3>
<h3>Bubble sort worst case and best case O(n²)</h3>
<h3>Insertion sort worst case O(n²) and best case O(n)</h3>
  <pre>
#Bubble sort
def self.bubble(list)
  list.each_index do |i|
    (list.length - i - 1).times do |k|
      if list[k] > list[k + 1]
        #ruby parallel assignment (swap)
        list[k], list[k + 1] = list[k + 1], list[k]
      end
    end
  end
end

#Quick sort
def self.quick_sort(list)
  sl = list.clone
  return sl if sl.size <= 1
  pivot = sl.pop
  left, right = sl.partition { |e| e < pivot }
  quick_sort(left) + [pivot] + quick_sort(right)
end

#Merge sort
def self.merge_sort(list)
  return list if list.size < 2
  left = list[0, list.length/2]
  right = list[list.length/2, list.length]

  merge(merge_sort(left), merge_sort(right))
end

#Merge-operation
def self.merge(left, right)
  sorted_list = []
  until left.empty? || right.empty?
    #if left <= right index, add left, else right
    sorted_list << (left[0] <= right[0] ? left.shift : right.shift)
  end
  #combine lists together
  sorted_list.concat(left).concat(right)
end

#Insertion sort
def self.insert_sort(list)
  for i in 1..(list.length - 1)
    x = list[i]
    j = i - 1
    while j >= 0 and list[j] > x
      list[j + 1] = list[j] 
      j -= 1
    end
    list[j + 1] = x
  end
  list
end
  </pre>
</div>

app/views/sorts/new.html.erb
<h1>New sort</h1>

<%= render 'form' %>

<%= link_to 'Back', sorts_path %>

app/views/sorts/show.html.erb
<h2>Numbers in array are: <%= @sort.name %></h2>
<h2>N = <%= @sort.input %></h2>

<%= content_tag :div, "", id: "chart", data: {sort: @sort} %>

<%= link_to 'Back', sorts_path %>